### ISSUE TITLE
ParseFile doesn't work

### ISSUE THREAD

**Issue by RustyPotato** [pdwood/opsysp1#1]
This is on you Peter. Your tokens just breaks it up into chars. Did you test it?

**Comment by pdwood** [comment]
Right now it just creates processes and doesn't store them anywhere, if that's what you mean, because I wrote it before I had access to your code.

**Comment by pdwood** [comment]
Ah, I see. It was interpreting the pipe "|" as a special character in a regex. I escaped it, so the method works now.
