### ISSUE TITLE
Project Doesn't Run on Basic Commands

### ISSUE THREAD

**Issue by RustyPotato** [pdwood/opsysp1#3]
I compiled the code generically with 
'javac *.java'
Compiles normally into classes. However, running it with: 
 'java Project1.class'
Doesn't work. This is an issue primarily because that is likely what the server will be doing.

**Comment by pdwood** [comment]
That's because you didn't give it arguments.

(It should print out something like "ERROR: No input files" in that case.)

**Comment by RustyPotato** [comment]
Error: Could not find or load main class Project1.class

**Comment by pdwood** [comment]
That's very weird.

**Comment by RustyPotato** [comment]
We fixed this in commit 4137700a8e3dbb1e3e232589ca9c7364840448c3.
